// <auto-generated />
using System;
using BackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(PCShopContext))]
    [Migration("20210113170239_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BackEnd.Models.Motherboard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Graficka_Kartica");

                    b.Property<string>("cpu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Procesor");

                    b.Property<string>("maticna")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime_Maticne");

                    b.Property<int>("maxNVME")
                        .HasColumnType("int")
                        .HasColumnName("Max_NVME");

                    b.Property<int>("maxRam")
                        .HasColumnType("int")
                        .HasColumnName("Max_Ram");

                    b.Property<int>("maxSATA")
                        .HasColumnType("int")
                        .HasColumnName("Max_Sata");

                    b.Property<int>("ramSlots")
                        .HasColumnType("int")
                        .HasColumnName("Broj_Ram_Slota");

                    b.HasKey("ID");

                    b.ToTable("Maticna_Ploca");
                });

            modelBuilder.Entity("BackEnd.Models.NVME", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("MotherboardID")
                        .HasColumnType("int");

                    b.Property<int>("Nvme")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MotherboardID");

                    b.ToTable("NVME");
                });

            modelBuilder.Entity("BackEnd.Models.PC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Case")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kuciste");

                    b.Property<string>("Cena")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cena");

                    b.Property<int>("MotherboardID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<string>("PSU")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Napajanje");

                    b.Property<int?>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MotherboardID")
                        .IsUnique();

                    b.HasIndex("WarehouseID");

                    b.ToTable("Racunari");
                });

            modelBuilder.Entity("BackEnd.Models.RAM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("MotherboardID")
                        .HasColumnType("int");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MotherboardID");

                    b.ToTable("RAM");
                });

            modelBuilder.Entity("BackEnd.Models.SATA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("MotherboardID")
                        .HasColumnType("int");

                    b.Property<int>("Sata")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MotherboardID");

                    b.ToTable("SATA");
                });

            modelBuilder.Entity("BackEnd.Models.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("PC_Warehouse");
                });

            modelBuilder.Entity("BackEnd.Models.NVME", b =>
                {
                    b.HasOne("BackEnd.Models.Motherboard", null)
                        .WithMany("NVME")
                        .HasForeignKey("MotherboardID");
                });

            modelBuilder.Entity("BackEnd.Models.PC", b =>
                {
                    b.HasOne("BackEnd.Models.Motherboard", "Motherboard")
                        .WithOne("PC")
                        .HasForeignKey("BackEnd.Models.PC", "MotherboardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Warehouse", "Warehouse")
                        .WithMany("Racunari")
                        .HasForeignKey("WarehouseID");

                    b.Navigation("Motherboard");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackEnd.Models.RAM", b =>
                {
                    b.HasOne("BackEnd.Models.Motherboard", null)
                        .WithMany("RAM")
                        .HasForeignKey("MotherboardID");
                });

            modelBuilder.Entity("BackEnd.Models.SATA", b =>
                {
                    b.HasOne("BackEnd.Models.Motherboard", null)
                        .WithMany("SATA")
                        .HasForeignKey("MotherboardID");
                });

            modelBuilder.Entity("BackEnd.Models.Motherboard", b =>
                {
                    b.Navigation("NVME");

                    b.Navigation("PC");

                    b.Navigation("RAM");

                    b.Navigation("SATA");
                });

            modelBuilder.Entity("BackEnd.Models.Warehouse", b =>
                {
                    b.Navigation("Racunari");
                });
#pragma warning restore 612, 618
        }
    }
}
